[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/upload-to-drive"
  to = "/.netlify/functions/upload-to-drive"
  status = 200

[[redirects]]
  from = "/api/submit-to-close"
  to = "/.netlify/functions/submit-to-close"
  status = 200

[[redirects]]
  from = "/api/send-kit-email"
  to = "/.netlify/functions/send-kit-email"
  status = 200

[[functions]]
  name = "newsletter-send-15"
  schedule = "0 9 15 * *"

[[functions]]
  name = "newsletter-send-28"
  schedule = "0 9 28 * *"

[[functions]]
  name = "newsletter-send-01"
  schedule = "0 9 1 * *"

[[functions]]
  name = "newsletter-send-06"
  schedule = "0 9 6 * *"
